### ISSUE TITLE
termux-notification not doing anything

### ISSUE THREAD

**Issue by srajasimman** [termux/termux-api#133]
Hi
after upgrading oreo termux-api didn't working for me. but after updating termux-am its working. but still termux-notification not working.

![image](https://transfer.sh/gWj1Y/termux-notification.gif)

kindly help me plz

**Comment by MMaster** [comment]
I've already left this comment on old closed issue of termux-api not working in Oreo (my fault) so I will just post it here since its relevant to this issue:

termux-notification definitely doesn't work on Oreo. Unfortunately while I can read code and know what needs to be done I don't have Android dev. environment setup so the best I can do right now is provide info on what needs to be done and hope that some good samaritan will do it.

After reviewing the termux-api code I found the issue. Android O update requires you to setup channel for notifications. I found out that NotificationAPI doesn't do this.

Without going into too much detail and just repeating what someone else has already said, answer to this SO question explains very well what needs to be done in order to make it work again on Oreo:
https://stackoverflow.com/questions/43093260/notification-not-showing-in-android-8-oreo/44534559

Hope this helps.

**Comment by nate2014jatc** [comment]
Howdy, just trying to bump this.

I'm another Oreo user that's trying to set up some scripts that depend on termux-notification to function.

**Comment by msdos** [comment]
Shouldn't this issue be closed since it's fixed in #173?

**Comment by Grimler91** [comment]
@msdos thanks!
