### ISSUE TITLE
Various commands cut off after the first word. (termux-clipboard-set, termux-notification, termux-dialog)

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#18]
Hi. I've noticed this today:
```
$ echo "Hello World" | termux-clipboard-set
$ termux-clipboard-get
Hello
$ termux-clipboard-set "Foo Bar"
$ termux-clipboard-get
Foo
```

**Comment by JKathmann** [comment]
Hi. I've noticed a similar problem today:

```
$ termux-notification -t "Foo Bar" -c "Hello World"
-> Foo

$ termux-notification -c "Hello World" -t "Foo Bar"
-> Hello
```

**Comment by Neo-Oli** [comment]
Ah yes, I did some more testing. `termux-dialog` is also affected. 
`termux-dialog -t "Hello World"`
-> Hello

**Comment by cathalgarvey** [comment]
Can corroborate this from go-termux; Calling `termux.Notification("Foo bar", "", "", "")` yields a notification entitled "Foo"

**Comment by cathalgarvey** [comment]
Can also confirm this for `termux.ClipboardSet`.

**Comment by JKathmann** [comment]
After some investigation, i found that fornwall has changed the file `termux-packages/packages/termux-api/termux-api.c` .
New is the call `/data/data/com.termux/files/usr/bin/am` instead `/system/bin/am` . 
In the file `/data/data/com.termux/files/usr/bin/am` the quotes around the parameter $@ are missing.
After changing from `$@` to `"$@"` commands run as usual.

**Comment by fornwall** [comment]
Thanks, this should now be fixed in the latest `termux-tools` package which is available through an `apt update && apt upgrade`.

The `termux-clipboard-set` command has been modified to either send all arguments, as in `termux-clipboard-set hello clipboard world`, or if no arguments are given the input is read from stdin for easier piping as in `cat myfile | termux-clipboard-set`.

The `termux-sms-send` command has likewise been updated to either take text through arguments or from stdin.
