### ISSUE TITLE
gpg-agent via OpenKeychain

### ISSUE THREAD

**Issue by 532910** [termux/termux-api#230]
Please make gnupg agent to use OpenKeychain.

Similar like [termbot](https://github.com/open-keychain/termbot) does. 

ssh-agent issue: #262

**Comment by c-e-p-x-u-o** [comment]
related  #823

**Comment by DDoSolitary** [comment]
Hello, I'm considering working on this when I get some spare time (maybe this summer).

Just some facts:

- I'm mainly a desktop dev who knows nothing about Android development so it might take some time learning before I actually start working on this.
- This repo seems to be mainly for exposing Android APIs in termux, I don't know if PRs for a third party's API would be accepted.
- OpenKeychain's OpenPGP API is quite high-level which directly creates PGP messages but the gpg-agent protocol is designed to process low-level crypto operations. So it would be extremely hard to implement a new agent without low-level APIs added to OpenKeychain.
- Implementing ssh-agent would be much easier because [OpenKeychain does provides SSH authentication API](https://github.com/open-keychain/open-keychain/blob/master/sshauthentication-api/src/main/java/org/openintents/ssh/authentication/SshAuthenticationApi.java). However, there's no documentation for this API and the only reference available is the source code of termbot.

**Comment by 532910** [comment]
> Implementing ssh-agent would be much easier because [OpenKeychain does provides SSH authentication API](https://github.com/open-keychain/open-keychain/blob/master/sshauthentication-api/src/main/java/org/openintents/ssh/authentication/SshAuthenticationApi.java). However, there's no documentation for this API and the only reference available is the source code of termbot.

As gpg-agent can emulate ssh-agent the idea was to customize gpg-agent to use OpenKeychain as a backend.

But if ssh-agent is much easier in implementation I the issue should be splited in two. As ssh-agent is more useful and more frequently used. And gpg-agent good to have too.

**Comment by 532910** [comment]
I've created a separate issue for ssh-agent: #262

**Comment by DDoSolitary** [comment]
A pre-alpha relase which supports SSH authentication is ready: DDoSolitary/OkcAgent#1
Support for `gpg-agent` will be introduced (if possible) after the SSH part gets stabilized and polished.

**Comment by DDoSolitary** [comment]
Both GPG and SSH support is available now in dev releases

**Comment by 532910** [comment]
https://github.com/DDoSolitary/OkcAgent

**Comment by auscompgeek** [comment]
Would be nice to have those tools in the termux repo...

**Comment by 532910** [comment]
> Would be nice to have those tools in the termux repo...

https://github.com/termux/termux-packages/issues/4352

**Comment by 532910** [comment]
OkcAgent looks abandoned and works bad.

**Comment by DDoSolitary** [comment]
Not abandoned yet. I just can't have much time to fix it...
Probably I will find some time to work on it this summer

**Comment by 532910** [comment]
It's good! But it crashes a lot and hardly usable, so I'll leave this issue open to attract attention.

**Comment by DDoSolitary** [comment]
It worked pretty well when I tested it on Android 9 (which was the latest Android when I wrote it), but stopped working on Android 10, which [restricts apps from starting activities from background](https://developer.android.com/guide/components/activities/background-starts).

So I have to rewrite the code that brings up OkcAgents from Termux. It is currently done by: "am broadcast" from Termux -> broadcast receiver -> start a foreground service to handle connections from Termux (so far so good) -> start activities to ask for user input (passphrase, NFC, etc) (not allowed on Android 10).

**Comment by 532910** [comment]
I'm still on Android 9.

**Comment by DDoSolitary** [comment]
Then that is pretty strange. I'll look into it.

**Comment by 532910** [comment]
OK, I'll try to debug it and provide more details.

**Comment by 532910** [comment]
@DDoSolitary https://github.com/DDoSolitary/OkcAgent/issues/6

**Comment by 532910** [comment]
OkcAgent is mostly usable
