### ISSUE TITLE
Bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied

### ISSUE THREAD

**Issue by badrshah** [termux/termux-api#269]
Despite having a rooted device this is what termux shows me.

Device: Samsung's Galaxy J5 SM-J500H 
Android version: 6.0.1
Root type: system less root (SuperSU)

![termux](https://user-images.githubusercontent.com/10578191/58459274-6d1eb900-8144-11e9-97d5-ba5eee262949.png)

**Comment by Grimler91** [comment]
Necessary environmental variables aren't set. Use `tsu -a` or `tsu -p` instead

**Comment by badrshah** [comment]
tsu -a
Bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied

tsu -p
bash: /system/bin/ls: Permission denied

**Comment by Grimler91** [comment]
Then I don't really know, might be something weird with your superSU version

**Comment by badrshah** [comment]
yeah maybe thats why you closed this issue -_-

**Comment by xeffyr** [comment]
Try `unset LD_PRELOAD`.

**Comment by Grimler91** [comment]
Hm, I can reproduce the problem on my android 9 phone, but I would guess that it is some problem with the SU version, or selinux (but not likely since OP has problems on android 6).

The permission denied only happens from a termux shell, running termux binaries from a /system/bin/sh shell works fine (so executing `/sbin/su` and then `/data/data/com.termux/files/usr/bin/ls` works fine but `/sbin/su` and then `/data/data/com.termux/files/usr/bin/bash` followed by `/data/data/com.termux/files/usr/bin/ls` gives permission denied)

**Comment by xeffyr** [comment]
@Grimler91 Does `unset LD_PRELOAD` (disabling termux-exec) helps ?

**Comment by Grimler91** [comment]
@xeffyr No, no change unfortunately

**Comment by Grimler91** [comment]
I've updated my rom and these problems are gone. I'm using magisk for root both now and before so this seem to be a rom problem

**Comment by Getmoneyman** [comment]
I need help I am completely new and I want to start mining bitcoin

**Comment by Ayanansari07** [comment]
DarkFly
bash: /data/data/com.termux/files/usr/bin/DarkFly: Permission denied
