### ISSUE TITLE
Feature: installing apk files via cli

### ISSUE THREAD

**Issue by nikitabobko** [termux/termux-api#324]
**Feature description**
It would be nice if there was a possibility for installing arbitrary apk files via cli in Termux.

**Reference implementation**
Something like `pkg install /path/to/apk`. Either, separate command can be introduced different from `pkg` because `pkg` manages Termux packages not installed apks but, honestly, I think that nothing would be bad if this ability was added right to `pkg`.

**Comment by kcubeterm** [comment]
But it's require root,

**Comment by nikitabobko** [comment]
> But it's require root

Haven't you ever installed apk via file manager? It works without root

**Comment by AbdullahM0hamed** [comment]
As far as I'm aware, @nikitabobko is correct.

I have tested that adding `<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />` allows me to perform the following command:

`am start -a android.intent.action.INSTALL_PACKAGE -d file:///path/to/app.apk`

Which launches it via the package installer (however, it is true that `pm install /path/to/apk` does not work).

**Comment by nacho00112** [comment]
Why you add this to termux:api instead of adding directly in termux? This is forcing the people to have the two apps without need

**Comment by agnostic-apollo** [comment]
Termux app also requests `REQUEST_INSTALL_PACKAGES` permission.

https://github.com/termux/termux-app/commit/93a5bf8d2905e227fac07630b30fb4a6da4e1145

**Comment by nacho00112** [comment]
This don't worked for me `am start -a android.intent.action.INSTALL_PACKAGE -d file:///path/to/app.apk` exits with code status 1
Also `termux-open` don't work because the application installer open and immediately stop, to solve this i had to modify `/.termux/termux.properties` and uncomment the line `allow-external-apps = true` after this `termux-open` worked opening the install prompt correctly, but  `am start -a android.intent.action.INSTALL_PACKAGE -d file:///path/to/app.apk` still don't work

**Comment by nacho00112** [comment]
Now it works, i ignored the "file:///" in the command `am start -a android.intent.action.INSTALL_PACKAGE -d file:///path/to/app.apk` but now it works hehe
