### ISSUE TITLE
[question] is there any way to judge a temux-api can work normally not hang?

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-api#402]
<https://github.com/romkatv/powerlevel10k/pull/1289#issuecomment-792236680>

> termux-battery-status hangs by default unless Termux:API is installed and
> given extra permissions. Thus, it's unsafe to invoke it without first
> ensuring that it won't hang. This is a deal breaker.

is there any way to judge a temux-api can work normally not hang?

Thanks!

**Comment by Efreak** [comment]
Check for existence of termux-api binary: `[ -x $PREFIX/libexec/termux-api ] && do_something`

**Comment by Freed-Wu** [comment]
Sorry for late. :(

it cannot work for me.

```
❯ tsu
❯ [ -x $PREFIX/libexec/termux-api ] && echo 1
1
# it will hang
❯ termux-wifi-connectioninfo
^C
```

**Comment by Grimler91** [comment]
Why are you running it as root? There is no reason to do so, I guess that is the cause of the issue

**Comment by xeffyr** [comment]
`[ -x $PREFIX/libexec/termux-api ]` is not the right way to check whether Termux:API is installed. It consists of 2 sides, client (termux-api binary) and backend which is Termux:API add-on application. If the latter one doesn't exist, `termux-api` will hang.

**Comment by agnostic-apollo** [comment]
Running `pm path com.termux.api` should give you the apk installation path for `Termux:API` and is the reliable way to know for sure. It exits with exit code `1` if not found. But on newer android versions, you will get `cmd: Failure calling service package: Failed transaction` error since normal apps users can't run it, but privileged users like `shell` (use `adb` from [`android-tools`](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/) package) or `root` can.

```
if pm path com.termux.api 1>/dev/null; then
    echo installed
fi
```

```
if su -c 'pm path com.termux.api 1>/dev/null'; then
    echo installed
fi
```

When running with `adb`, ensure you have already run `adb connect`. Also run `adb devices` and use the serial found for your current device and pass that as `-s` to `adb shell` command, otherwise if more than one devices found, `adb` command will fail with `adb: more than one device/emulator`.
```
if adb -s emulator-5554 shell 'pm path com.termux.api 1>/dev/null'; then
    echo installed
fi
```

Moreover, above way is also slow, since it has to make a call to the android package manager. Faster but slightly unreliable way would be to check if the `/data/data/com.termux.api` path exists which android should create at android app installation time.

`[ -d /data/data/com.termux.api ] && echo 1`

```
if [ -d /data/data/com.termux.api ]; then
    echo installed
fi
```

**Comment by Freed-Wu** [comment]
however, for non-termux user (as for me, it is u0_a205), Termux:API will hang
whatever i do. why this phenomenon happen?

and if it cannot work for non-termux user, why it must hang not return a
non-zero value?

thanks.

**Comment by lgommans** [comment]
This issue is being misunderstood I think. The replies are about detecting whether it's installed, but it seems the issue is that the process hangs.

I have a similar problem. Not everything hangs, for example reading the camera info works fine, but the sensors hang indefinitely when I just try to list them. Running `$PREFIX/libexec/termux-api` says an argument was expected, and when I do (no matter what it is) it just hangs forever. Running `termux-sensor` gives a help text, but `termux-sensor -l` hangs indefinitely. Using `strace -f termux-sensor -l`, there's a *ton* of output that I frankly can't understand (sometimes I see something helpful like waiting for a file or I can trace that it waits for a network packet) and it ends up hanging on `accept4(3, `. Not sure if that's an identical problem as what OP describes or a different one.

**Comment by Freed-Wu** [comment]
> This issue is being misunderstood I think. The replies are about detecting whether it's installed, but it seems the issue is that the process hangs.
> 
> I have a similar (or the same?) problem. Not everything hangs...

I agree with you. I met the hang problem in both adb shell and terminal (after su). I have not done more researches about it. I feel confused by this situation...

**Comment by lgommans** [comment]
@Freed-Wu Check logcat if you have the same error.

Also I might recommend deepl.com for translation since you seem to not have understood my message fully. It is also hard to understand you. Deepl's english<>dutch translation is really good and it looks like they support chinese as well.

---

@Freed-Wu 检查logcat，如果你有同样的错误。

另外我可能会推荐deepl.com进行翻译，因为你似乎没有完全理解我的信息。我也很难理解你。Deepl的英语<>荷兰语翻译真的很好，而且看起来他们也支持中文。

**Comment by agnostic-apollo** [comment]
>and if it cannot work for non-termux user, why it must hang not return a non-zero value?

The [`termux-api`](https://github.com/termux/termux-api-package/blob/master/termux-api.c) binary interacts with the `Termux:API` app via sockets, the app isn't running with root, so communications isn't possible, the app can't send back the result, hence command hangs. There are no checks in place in `termux-api` for whether caller is a non-termux user or not, so that a command isn't even sent to the app. Some commands like `apt` do have checks.

```
2021-08-07 18:13:34.651 8606-8637/com.termux.api E/termux-api: Error in ResultReturner
    java.io.IOException: Permission denied
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
        at android.net.LocalSocket.connect(LocalSocket.java:147)
        at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:122)
        at com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(Unknown Source:8)
        at java.lang.Thread.run(Thread.java:919)
```

Basically, do not run with root. Running something like `su 10xxx -c 'termux-wifi-connectioninfo'` to run as termux user will fail as well, due to wrong capabilities/privileges, you will need something like [this](https://android.stackexchange.com/questions/217016/how-to-run-a-program-in-an-app-context-with-magisk) to work, which requires patching selinux policy as well. Moreover, termux doesn't provide `setpriv` and the mirrors for the one in stackexchange comment have expired, but attaching it. The one I compiled for termux from `termux-packages` was failing on android `7`, but seemed to work on android `10` rooted emulator but magisk root script doesn't install `supolicy` so can't fully test it. Will look into it in future. 

[setpriv_static_aarch64_v2.33.296-14690.zip](https://github.com/termux/termux-api/files/7040690/setpriv_static_aarch64_v2.33.296-14690.zip)

>E termux-api: java.lang.IllegalStateException: Not allowed to start service Intent { act=list cmp=com.termux.api/.SensorAPI$SensorReaderService (has extras) }: app is in background uid UidRecord{9cef9ac u0a159 RCVR bg:+1h2m30s337ms idle change:uncached procs:2 seq(0,0,0)}

Have you disabled battery optimizations for termux-api AND termux app? https://dontkillmyapp.com/

**Comment by agnostic-apollo** [comment]
Although, if running with `root`, then sending `RUN_COMMAND` intent in background mode that stores results in files should work. That way, termux app process would initiate the sockets so should work. In your root script, just wait for the result to be written to the output files in a while loop. Check https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent and termux/termux-app@2aafcf84

**Comment by Freed-Wu** [comment]
> The termux-api binary interacts with the Termux:API app via sockets, the app isn't running with root, so communications isn't possible, the app can't send back the result, hence command hangs.

Thanks for your answer!

> There are no checks in place in termux-api for whether caller is a non-termux user or not, so that a command isn't even sent to the app. Some commands like apt do have checks.

I know. If there are checks in termux-api, it will be great.

> Basically, do not run with root... Will look into it in future.

Thanks!

> Although, if running with root, then sending RUN_COMMAND intent in background mode that stores results in files should work.

Great. Thanks for your answer.
