### ISSUE TITLE
Nothing to do with Termux:API add-on. Termux is not affiliated with Shodan, neither vice-versa.

### ISSUE THREAD

**Issue by xzj8b3** [termux/termux-api#409]
Nothing to do with Termux:API add-on. Termux is not affiliated with Shodan, neither vice-versa.

Your problem is invalid API key. You should log in to your account, copy the provided API key and paste it on command line.

_Originally posted by @xeffyr in https://github.com/termux/termux-api/issues/408#issuecomment-818315164_
I understood that, but the key is valid because in Fedora it works and in the account I tried to regenerate it but on notebook it works .. It is wrong with termux and it is strange because in the past I have always used it

**Comment by Grimler91** [comment]
I have no idea what shodan is, and I can't see anything in your screenshot that indicates that there is a termux issue.
Since the error you are seeing is thrown from shodan you should probably ask the creators of that program for help. 

Also, it is a good idea not to share (private) API keys in screenshots.
