### ISSUE TITLE
Termux-clipboard-get does not work in background.

### ISSUE THREAD

**Issue by jonathan-franc** [termux/termux-api#452]
**Problem description**
Hi.  I am trying to get data from the clipboard and it works until I minimize the application.  At the same time, other requests, for example: termux-battery-status, work properly and give information no matter what.

For the test, I am using a bash script:

```
while :
do
sleep 4
echo "$(termux-clipboard-get)"
echo "$(termux-battery-status)"
echo "$(date)"
done
```

After running the script, I get all the data, but when I collapse Termux, the data still continues to go to the log, but without the clipboard value.
Can I overcome this limitation?

**Additional information**

* Termux application version: 0.117
* Android OS version: 10
* Device model: Honor 10i

**Comment by agnostic-apollo** [comment]
You are welcome.

**Comment by haarp** [comment]
Seems there is a way to get the permissions via ADB, but it looks like it requires code changes too: https://github.com/clipto-pro/Android/issues/11

Someone with more knowlege needs to have a look at it, so we can reopen this :)

**Comment by haarp** [comment]
Thanks a lot @agnostic-apollo, looking forward to this! :)

Do you have an example on how to grab the clipboard content via `service call`? `service call clipboard 1` doesn't seem to work, at least on my Android 10.

**Comment by haarp** [comment]
Wow, Android development is ugly. Thanks @agnostic-apollo, you convinced me to wait :)

**Comment by FalconSN** [comment]
I've stumbled upon this too while writing a bash script, and couldn't find a way around this.
> Basically you will have to wait until I release it.

How is the progress?

**Comment by scientiac** [comment]
any progress on this?... maybe a workaround using root ?

**Comment by twaik** [comment]
Progress is not possible. Android restricts it.

**Comment by agnostic-apollo** [comment]
Progress is possible with adb/root, check comment above. Release will happen after app updates.

**Comment by twaik** [comment]
Adb and root are not an option for most of people.

**Comment by agnostic-apollo** [comment]
The guy literally asked for workaround with root. And adb wireless is available on android `>= 11` and needs to be setup once per boot, so is easily available if someone needs it.

**Comment by twaik** [comment]
Ok, it seems like it is a viable solution. What about https://github.com/clipto-pro/Android/issues/11 ? It seems like it has to be setup once per application installation.

**Comment by agnostic-apollo** [comment]
Tasker also uses that hack to make itself the keyboard when it detects log entry for clipboard copying, but it requires lot of workarounds on different devices as messes with keyboard, logcat command also shows popup on android 13 unless run with adb/root. The service command or using shizuku shell app process to call `getPrimaryClip()` would be much simpler.

**Comment by twaik** [comment]
> ```shell
> ANDROID__SDK_VERSION=29
> 
> # If android >= 12
> if [ "$ANDROID__SDK_VERSION" -ge 31 ]; then
>     # Method 4 `ClipData getPrimaryClip(String pkg, int userId)`
>     # https://cs.android.com/android/platform/superproject/+/android-12.0.0_r4:frameworks/base/core/java/android/content/IClipboard.aidl;l=33
>     get_primary_clip_command='clipboard 4 s16 "com.android.shell" i32 0'
> # If android >= 10
> elif [ "$ANDROID__SDK_VERSION" -ge 29 ]; then
>     # Method 3 `ClipData getPrimaryClip(String pkg, int userId)`
>     # https://cs.android.com/android/platform/superproject/+/android-10.0.0_r47:frameworks/base/core/java/android/content/IClipboard.aidl;l=31
>     get_primary_clip_command='clipboard 3 s16 "com.android.shell" i32 0'
> # If android = 9
> elif [ "$ANDROID__SDK_VERSION" -eq 28 ]; then
>     # Method 3 `ClipData getPrimaryClip(String pkg)`
>     # https://cs.android.com/android/platform/superproject/+/android-9.0.0_r61:frameworks/base/core/java/android/content/IClipboard.aidl;l=31
>     get_primary_clip_command='clipboard 3 s16 "com.android.shell"'
> else
>     # Method 2 `ClipData getPrimaryClip(String pkg)`
>     # https://cs.android.com/android/platform/superproject/+/android-7.0.0_r36:frameworks/base/core/java/android/content/IClipboard.aidl;l=30
>     get_primary_clip_command='clipboard 2 s16 "com.android.shell"'
> fi
> 
> adb shell "service call $get_primary_clip_command"
> ```

This can work, but vendors can change codes of transactions. Probably better way will be not to deduce code depending on android version and get it directly from `IClipboard` class. It will be like 
```
Binder mBinder = new Binder("android.content.IClipboard") {
    protected boolean onTransact(int code, @androidx.annotation.NonNull Parcel data, Parcel reply, int flags) {
        data.enforceInterface("android.content.IClipboard");
        Log.d("android.content.IClipboard", "code is " + code);
        return true;
    }
};

(new android.content.IClipboard.Stub.Proxy(obj)).getPrimaryClip(/* pkg */ null, /* attributionTag */ null, /* userId */ 0, /* deviceId */ 0);
```

BUT `android.content.IClipboard.Stub.Proxy` is private member of `android.content.IClipboard.Stub` stub so it will be better to use reflection or JNI to instantiate this.

Using Shizuku maybe a bad option too.
[This code](https://cs.android.com/android/platform/superproject/main/+/main:out/soong/.intermediates/frameworks/base/framework-minus-apex-intdefs/android_common/e18b8e8d84cb9f664aa09a397b08c165/xref50/srcjars.xref/android/content/IClipboard.java;l=87-97;drc=71c806d9f13939dda9ac9648171bb20849cf96f6;bpv=0)
```
    /**
     * Cast an IBinder object into an android.content.IClipboard interface,
     * generating a proxy if needed.
     */
    public static android.content.IClipboard asInterface(android.os.IBinder obj)
    {
      if ((obj==null)) {
        return null;
      }
      android.os.IInterface iin = obj.queryLocalInterface(DESCRIPTOR);
      if (((iin!=null)&&(iin instanceof android.content.IClipboard))) {
        return ((android.content.IClipboard)iin);
      }
      return new android.content.IClipboard.Stub.Proxy(obj);
    }
```
restricts instantiating IClipboard for binders other than `android.content.IClipboard` (but you may override it by using compile-only dependencies replaced by real classes in runtime and making your class extend `android.content.IClipboard`).

Also there may be a better Shizuku-like option.
You can instantiate some piece of code inside com.termux (or com.termux.api) app as adb or shell with 
```
CLASSPATH="$(pm path com.termux | cut -d: -f2)" app_process / com.termux.PrivilegedShellEntryPoint some args
```

Which will send broadcast to termux's service (with the help of parts of `termux-am` code). This broadcast will contain Binder which can be used for communicating this privileged (root or adb) process. This process will not be killed by OOM or Phantom Process killers and may run in background forever even in the case if `com.termux` application is force-stopped or even deleted from device, until device is rebooted. But it can be killed with adb daemon (in the case if it is started with ADB).
And it will have the same requirements and starting instructions as in case with Shizuku, but will have no Shizuku or any other dependency. 

I am not sure but maybe root or adb process may (somehow) register BroadcastReceiver which can be used as some kind of Bound Service. I mean you can send it ordered broadcast to get clipboard, or can trigger establishing communication channel (with sending broadcast).

**Comment by twaik** [comment]
As far as I understand the best option to get clipboard is to use focused window. Can we simply make termux-api create some focusable overlay which takes focus on its appearing, read clipboard and disappear (and drop the focus)? Yes, it will require Draw over other apps permission, but it will not require root or adb to make it work.

**Comment by agnostic-apollo** [comment]
> This can work, but vendors can change codes of transactions.

I am aware of that, my scripts automatically download aidl files from AOSP or lineageOS sources (check https://github.com/T-vK/android-svc/issues/4 for reference). If user expects codes to be different, then a separate app generates aidl files of all services using reflection. A sample file generated for `android/content/IClipboard.aidl` is below.

```java
void setPrimaryClip(ClipData par1, String par2, int par3);
void clearPrimaryClip(String par1, int par2);
ClipData getPrimaryClip(String par1, int par2);
ClipDescription getPrimaryClipDescription(String par1, int par2);
boolean hasPrimaryClip(String par1, int par2);
void addPrimaryClipChangedListener(IOnPrimaryClipChangedListener par1, String par2, int par3);
void removePrimaryClipChangedListener(IOnPrimaryClipChangedListener par1, String par2, int par3);
boolean hasClipboardText(String par1, int par2);
```

>Also there may be a better Shizuku-like option.

I was going for efficiency, hence everything is done in the script locally to call service command and decoding the hex itself, with only necessary calls to util binaries. Moreover, many methods run fine without root and with root and adb is not needed, and many methods only return `void`, so hex only contains transaction result. A privileged Shizuku shell app process or `app_process` started via `adb` shell way is doable too, but there is overhead in calling them via an API and then getting back result. Moreover, decoding is not possible for all complex/nested java objects, maybe just starting an `app_process` to decode hex could be used, would require somehow putting hex back into a `Parcel` somehow (`unmarshall()`) and then reading the object, or calling the service itself directly from privileged process so that hex is never involved and we get java object directly as result. Shell way to decode gives more control to user what needs to be decoded and printed, via function hooks, without having to do it later with some external json parser, currently java objects are stored as shell variables via an internal shell json library.

```shell
$ bash termux-asvc.sh call 'com.android.internal.telephony.ITelephony.dial("5555")'

$ bash termux-asvc.sh call --call-user="shell" -j 'android.content.pm.IPackageManager.getPackagesForUid' 10220
[
  "com.termux.window", 
  "com.termux.tasker", 
  "com.termux.gui", 
  "com.termux.widget", 
  "com.termux", 
  "com.termux.api", 
  "com.termux.styling"
]
$ bash termux-asvc.sh call --call-user="shell" -j 'android.content.pm.IPackageManager.getPackageUid' "com.termux" 0 0
{
  "mInt": 10220
}
$ bash termux-asvc.sh call --call-user="shell" -j 'android.content.pm.IPackageManager.getPackageGids' "com.termux" 0 0
[
  3003
]

$ bash termux-asvc.sh call --call-user="shell" 'android.content.IClipboard.getPrimaryClip' "com.android.shell" 0
{
  "mClipDescription": {
    "mLabel": null, 
    "mMimeTypes": [
      "text/plain"
    ], 
    "mExtras": null, 
    "mTimeStamp": 5943865216515432462
  }, 
  "mItems": [
    {
      "mText": {
        "String": "termux in clip!", 
        "0_SpellCheckSpan": {
          "mSpellCheckInProgress": false
        }
      }, 
      "mHtmlText": null, 
      "mIntent": null, 
      "mUri": null
    }
  ]
}

$ bash termux-asvc.sh call --call-user="shell" --print-func="printPrimaryClipText" --minimal-set-data 'android.content.IClipboard.getPrimaryClip' "com.android.shell" 0
termux in clip!
```

>As far as I understand the best option to get clipboard is to use focused window.

No, best way is adb or root. Focused window would be annoying to see every time and may get dismissed accidentally, etc and commands will fail, and there would be lot of delays. I also don't think an overlay is going to work, and fully interactive window is going to be needed.

The `ClipboardManager.getPrimaryClip()` method has the following access requirements. ([1](https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/clipboard/ClipboardService.java;l=619-626), [2](https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/clipboard/ClipboardService.java;l=1242))

- Can be accessed by default IME (keyboard) or currently focused app.
    - https://cs.android.com/android/_/android/platform/frameworks/base/+/a6b2d5caafd4a95c1029f2b16cded734c59ed38a
    - https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/wm/WindowManagerService.java;l=7997
    - https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/wm/DisplayContent.java;l=566-571
    - https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/wm/WindowState.java;l=290-291

- Can be accessed by the `shell` user for the [`com.android.shell` package](https://cs.android.com/android/_/android/platform/frameworks/base/+/refs/tags/android-14.0.0_r1:packages/Shell) as it has the `READ_CLIPBOARD_IN_BACKGROUND` permission. The permission has protection level `signature`, i.e can only be granted to apps signed with the platform signing key. The protection level `role` was also added for the permission in Android `13`, so that apps with the `SYSTEM_TEXT_INTELLIGENCE` role ([1](https://source.android.com/docs/core/permissions/android-roles), [2](https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:packages/modules/Permission/PermissionController/src/com/android/permissioncontroller/role/Role.md), [3](https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:packages/modules/Permission/PermissionController/src/com/android/permissioncontroller/role/service/RoleControllerServiceImpl.java;l=207), [4](https://cs.android.com/android/_/android/platform/packages/modules/Permission/+/refs/tags/android-14.0.0_r1:PermissionController/role-controller/java/com/android/role/controller/model/Role.java;l=560)) also have access, but that requires the app to be a system app and since role is `static` and `exclusive`, at most one application is allowed to be its holder and it must be defined in the [`config_systemTextIntelligence`](https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/core/res/res/values/config.xml;l=5971-5974) framework config value set during build time. ([1](https://cs.android.com/android/_/android/platform/packages/modules/Permission/+/refs/tags/android-14.0.0_r1:PermissionController/role-controller/java/com/android/role/controller/model/Role.java;l=608), [2](https://cs.android.com/android/_/android/platform/packages/modules/Permission/+/refs/tags/android-14.0.0_r1:PermissionController/role-controller/java/com/android/role/controller/model/Role.java;l=456)) The `config_systemTextIntelligence` value is set to Android System Intelligence (`com.google.android.as`) package on AVD and Google Pixels.
    - https://cs.android.com/android/_/android/platform/frameworks/base/+/bd175fe89132d5dbde1bf92d683eea22236c51fb
    - https://cs.android.com/android/_/android/platform/frameworks/base/+/4fa6711c0074e2628e4929d585764991a18cba89
    - https://cs.android.com/android/_/android/platform/packages/modules/Permission/+/7105ecc66b3257d59613de2a2133e4b7299fe114
    - https://cs.android.com/android/_/android/platform/frameworks/base/+/refs/tags/android-14.0.0_r1:core/res/AndroidManifest.xml;l=7126-7129
    - https://cs.android.com/android/_/android/platform/frameworks/base/+/refs/tags/android-14.0.0_r1:packages/Shell/AndroidManifest.xml;l=326
    - https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:packages/modules/Permission/PermissionController/res/xml/roles.xml;l=965-1002

- Cannot be accessed if device is locked.
    - https://cs.android.com/android/_/android/platform/frameworks/base/+/93d77b07c34077b6c403c459b7bb75933446a502

**Comment by SuggonM** [comment]
After failing to find a quick solution, I made an ugly workaround by creating a temporary floating window. (This just uses draw over other apps functionality from `Termux:Float`)

```sh
clipboard=$(ssh phone termux-clipboard-get)
if [ -z "$clipboard" ]; then
	ssh phone am startservice com.termux.window/.TermuxFloatService &> /dev/null
	clipboard=$(ssh phone termux-clipboard-get)
	(ssh phone am stopservice com.termux.window/.TermuxFloatService &> /dev/null &)
fi
echo "$clipboard"
```
Takes 5 secs at max to get the output but I'll rather accept the delay than wasting more time juggling between termux and the other app.

**Edit:** Created a gist for it with a slightly more efficient approach: https://gist.github.com/SuggonM/f08fb33a613601183c6354d193a83f00

**Comment by Benjamin-Loison** [comment]
[#issuecomment-3964563235](#issuecomment-3964563235) @SuggonM:

For reference on Fairphone 4 LineageOS 23.2 on an established SSH connection it takes 1.060s.

<details>
<summary>Bash script:</summary>

```bash
date +"%T.%3N"
clipboard=$(termux-clipboard-get)
if [ -z "$clipboard" ]
then
    SERVICE=com.termux.window/.TermuxFloatService
	am startservice $SERVICE > /dev/null
	clipboard=$(termux-clipboard-get)
	am stopservice $SERVICE &> /dev/null &
fi
echo "$clipboard"
date +"%T.%3N"
```
</details>
<details>
<summary>Output:</summary>

```
20:54:14.214
[1] 9154
My clipboard content
20:54:15.274
```
</details>

While `termux-clipboard-get` takes 0.270s while having Termux in foreground.

The Termux float is only shown for less than a second.

**Comment by SuggonM** [comment]
Setting up the said clipboard script into my device and then invoking it with `ssh phone ./clipboard-get.sh` brings down the average time from 3s to 2s. Not much of an improvement. In this case, I'm also having to add a `sleep 0.1` after the `startservice` command, otherwise it returns empty for whatever reason.

**Comment by Benjamin-Loison** [comment]
[Benjamin_Loison/ADB_clipboard](https://codeberg.org/Benjamin_Loison/ADB_clipboard)

> workarounds [the restriction introduced in Android 10 to require app being in foreground to access its clipboard content](https://developer.android.com/about/versions/10/privacy/changes#clipboard-data). This tool should works fine for lower Android versions too. Note that the screen must be turned on and user session unlocked to retrieve clipboard content. This tool does not temporarily show an app in foreground to workaround this restriction.

It does not rely on Termux, Termux:API, Termux:Float and SSH too.

It retrieves the clipboard content in 0.446s on Fairphone 4 LineageOS 23.2.
