### ISSUE TITLE
better access of files with SAF

### ISSUE THREAD

**Issue by tareksander** [termux/termux-api#475]
**Feature description**

termux-manage-folder: open a directory tree and returns the URI.  
termux-saf-ls: lists directories and files in a folder as JSON, returning the URI and metadata, so you can navigate the document tree.  
termux-saf-read: Reads a file from a URI and outputs it to stdout or a file.  
termux-saf-write: Writes stdin to a file from a URI, or to a new file if the parent directory URI and a name is specified.  

Example: `termux-saf-read <URI to file on the sd card> | gzip | termux-saf-write <URI to folder on the sd card> compressed.gz`

Another usage case for the user could be to periodically backup the home directory, compress it, encrypt it and safe it to google drive via SAF, completely automatic and without having to choose any location or moving the file yourself.  

The difference to `termux-storage-get` is that the files don't need to be saved temporarily, so you can use streaming programs to process large files efficiently, and because the app gets the permission to use the directory tree forever, there is no need to open a UI when a command is run, you can automate reading and writing from the SAF from the command line.  

You could also then make more high-level programs to build on top of that, e.g. storing all accessible folder URIs in a file and map them to paths and make utilities to work with those paths instead that internally call the URI-based programs, abstracting away the URIs and working with paths like `dir1/some/folders/deep/file.txt`, which is easier for the user to type.

It may also be possible to modify proot to "mount" a SAF directory, so you can access the files with programs that can't operate with stdin and stdout.

**Reference implementation**

Have you checked if the feature is accessible through the Android API?
https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE  
https://developer.android.com/training/data-storage/shared/documents-files

Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)  
[simple file manager](https://github.com/SimpleMobileTools/Simple-File-Manager) uses that to get access to the sd card.

**Comment by agnostic-apollo** [comment]
I think this was the wrapper I found https://github.com/YuriSizuku/AndroidSafFile and posted earlier. Maybe there are others.

**Comment by tareksander** [comment]
You need an Android Context to access the SAF. Isn't that the same problem `am` has in Termux? I don't think a C program that just spins up a JVM gets an App Context by the system. All solutions I found use JNI to call the Java implementations, but that isn't possible for a pure C program. I tried to create a JVM in C and the NDK doesn't even provide the function for that.

**Comment by navid-zamani** [comment]
This is so cumbersome for no reason.
Termux should just let me “mount” any SAF to ~/storage/…, the same way it does for the other things in there.

**Comment by sylirre** [comment]
@navid-zamani If something "obvious" isn't done, such decision likely has some ground behind.

Directories you see in ~/storage (aka `$HOME/storage`, don't confuse with `/storage`) are not mount points. They are symbolic links to system directories like `/storage/emulated/0`, `/storage/emulaed/0/DCIM`, `/storage/emulated/0/Music`, etc.

Moreover real mounting of SAF can't be done because:

1. `mount()` system call possible only for root user. *It worth to remember that Termux operates within Linux space, so all Linux rules apply and shell programs can't open volumes just like Android apps do.*
2. SAF doesn't provide file systems and doesn't operate on raw file system paths at all. This is API for accessing documents through content provider, effectively disqualifying it as a backend that can be easily mounted to file system by Linux.
