### ISSUE TITLE
All and any Termux API calls (except termux-info) do not return

### ISSUE THREAD

**Issue by arbrebinaire** [termux/termux-api#502]
Seem like I'm not the only one having this issue.

A call to `termux-battery-status` for instance does not return: it just hangs.

The only way to bring the API commands back to life: restart the phone.  After a while though, back to square one: futher calls do not return.

Android battery optimization was set to none.  All permissions were given.  Both the app and the termux-api executable are installed.

Question: I suppose there is an API daemon active when the commands are successful and that it is stopped somehow by Android at some point.  Is there a way to restart the daemon manually and not by restarting the phone?  I see there is a `termux-api-start` command (which returns a 0 code when called), but it does not fix the issue.

Thanks.

**Comment by tareksander** [comment]
If you try to use another api command while one hags, does the other one also hang?  
`termux-api-start` does start a daemon, but it's just so Android doesn't kill the whole Termux:API process as easily.  
If Android did terminate Termux:API, using another api command should be enough to get it back going. AFAIK Termux:API does all work on the main thread, so if one command happens to block the thread, others also would have to wait.

**Comment by Grimler91** [comment]
Which version of the app is installed? (github debug builds or from fdroid?)

**Comment by arbrebinaire** [comment]
> Which version of the app is installed? (github debug builds or from fdroid?)

It's the fdroid version (main and api app at their latest available version).

**Comment by agnostic-apollo** [comment]
> Termux:API does all work on the main thread, so if one command happens to block the thread, others also would have to wait.

No, separate threads are started for all commands.

https://github.com/termux/termux-api/blob/v0.50.1/app/src/main/java/com/termux/api/util/ResultReturner.java#L174

>When one command is used and hangs, another api command will also hang.

If your api commands crashed the app more than once within default 2mins, app process is force stopped and marked as a bad process and receivers not allowed to be restarted since close timed crashes means faulty app which can result in system instability and how it should be. The only way to restart the app is for user to manually start the app again, but since current F-Droid release does not have a launcher activity, there is no way to start the app again and issue isn't fixed until device is restarted.

A launcher activity has been added now, and some exceptions that may have crashed the app will be caught and a notification shown for them and for any uncaught exceptions as well. App will also show in DuraSpeed list due to launcher activity add. Will be available in next release. Users will have to do their part and report such crashes.

https://developer.android.com/about/versions/android-3.1.html#launchcontrols

Check f2c1342f, 3c1a6be8, 6112bf67, 4c5c27bb, cfbcde8f, termux/termux-app@5f005313, termux/termux-app@477b36ac

```
ActivityManager: Process com.termux.api has crashed too many times: killing!
ActivityManager: Killing 20478:com.termux.api/u0a181 (adj 905): crash
...
BroadcastQueue: Unable to launch app com.termux.api/10181 for broadcast Intent { flg=0x10 cmp=com.termux.api/.TermuxApiReceiver (has extras) }: process is bad
```

To confirm your issue if different (specially if related to DuraSpeed), run `logcat` command over adb or root when commands hang, guessing blindly is useless.

`adb logcat -d > logcat.txt`

Wait for next release and hopefully things will improve for users for some things.

You may also want to enabled `Always show crash log` enabled in developer options to at least know when app crashed.

**Comment by arbrebinaire** [comment]
> Will be available in next release

I appreciate the heads-up.

What valuable pieces of software Termux and the Termux:API are!  Good going.
