### ISSUE TITLE
termux-api is slow. 

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#63]
The termux-api commands are rather slow. 
```
$ time termux-notification --content "test"
termux-notification --content "test"  0.08s user 0.01s system 9% cpu 0.992 total
```
Is there anything that can be done to speed things up?
It is most noticable when updating notifications with rapidly changing content or for programs that interface with the clipboard a lot.

**Comment by Ferrisbane** [comment]
I'm having the same issue, some commands can take 40+ seconds (termux-infrared-transmit)

**Comment by Defragmented-Panda** [comment]
i have the same problem, same 1 second for termux-* commands and 2.5 seconds for nodejs launch(0.2 seconds on pc)

i suspect author have set 1 second delay to some actions that access android system. And nodejs(suppose to launch in 0.2 sec) makes 2 such actions. i guess he did it to fight some race condition that he cant check...

if we would collect more commands that have this delay, it would be easier to pinpoint why does termux have this delay

commands like ls, wget, chmod, whoami, date are instant (part of busybox and low level stuff)

ngrok (hamachi equivalent), python and vim also starts instantly. so disk operations and network access are instant too, even from pkg or downloaded binaries (non busibox stuff)

**Comment by xeffyr** [comment]
> i suspect author have set 1 second delay to some actions that access android system.

@Defragmented-Panda We don't setting delays - there no point to do this.
The reason why termux api commands take some time to launch is simple - we calling activity manager (like /system/bin/am) which actually creates an instance of DalvikVM. Since creation of dalvikvm instance is expensive, you may observe a some delay before command will be actually started.

> And nodejs(suppose to launch in 0.2 sec) makes 2 such actions. i guess he did it to fight some race condition that he cant check...

Here you again wrong, there no manual delays. Most time nodejs spend on accessing/modifying memory - nothing strange here since it performs just-in-time compilation.

> commands and 2.5 seconds for nodejs launch(0.2 seconds on pc)

Never compare Android device with PC - **they are not interchangeable** even if your device has more cores than PC. Android cannot be comparable to real Linux distribution.

> commands like ls, wget, chmod, whoami, date are instant (part of busybox and low level stuff)

Of course, pure C programs are fast.

> python and vim also starts instantly.

About python... Just run `pip list` and you will be surprised - it has delay too since it is interpreted language.

***

### Summary

1. Before accusing author (or other devs) of `specially setting a delay`, make sure that you have enough proof, otherwise you will look crazy =). You can always check package patches and build scripts in https://github.com/termux/termux-packages and open issue if you found something wrong.

2. To improve speed of Termux API we have to run it as service in background and use sockets for communication. **This is currently not implemented**, but there some work on this. See https://github.com/Epictek/termux-api/commit/6a16ace08dec6922ce88806c54e52c6fea706155.

**Comment by kijikeki** [comment]
What if all executables were dlopened from libtermux? (This may also be useful for when Android Q comes out afaik)

**Comment by xeffyr** [comment]
> What if all executables were dlopened from libtermux, run them as a part of com.termux?

Offtopic, btw.
Dlopen will not speed up the Termux:API.

***

And since Android Q still allows to have binaries in native lib dir, we don't need dlopen() to load executables. Dlopen also suffers from restriction (which applied on Android 8 perhaps as I have it) which prevents loading libraries from arbitrary locations. So with trying to dlopen() something from JNI (!) you will end with following error:
```
03-24 16:26:09.142 21917 21917 E linker  : library "/sdcard/dash.so" ("/storage/emulated/0/dash.so") needed or dlopened by "/data/app/com.termux-ZWwtJiVLc0NYP8WepLzmiQ==/lib/arm64/libtermux.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.termux-ZWwtJiVLc0NYP8WepLzmiQ==/lib/arm64:/data/app/com.termux-ZWwtJiVLc0NYP8WepLzmiQ==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.termux"]
```

So dlopen() for now has zero benefits (why we should use it when executables still allowed ?) and some drawbacks and therefore will not be used.

**Comment by kijikeki** [comment]
Ah sorry

I meant loading with JNI yes. Instead of dlopen.. is mmap & mprotect viable? Android Q removes exec permission from the app's home dir, and the libdir is readonly, so...?

**Comment by traverseda** [comment]
Any progress on this? I'd find it useful for doing morse code over the vibrating-motor.

**Comment by tareksander** [comment]
I was unsatisfied with the startup time of the Termux:API programs and did some research:  
I manually stopped the Termux:API process and then timed `termux-battery-status` on my Fairphone 3 and Samsung Galaxy S7:  
S7: 0.9s  
FP3: 1.1s  
With the Termux:API process still running:  
S7: 0.7s  
FP3: 0.5s  
Running `am start -n com.termux/.app.TermuxActivity` to test the speed of `am`:  
S7: 0.6s  
FP3: 0.5s  
  
Them main culprit is indeed the creation of a DalvikVM.  
  
I implemented an alternative way to send commands to Termux:API and a dummy service you can start with `am` to keep the process running. The plugin opens a Unix server socket on a predefined address in the abstract Linux namespace and accepts connections from the same UID. You can then send the arguments you would pass to `am` over the socket, the plugin parses them and calls its own receiver with the constructed intent. If the parsing fails for some reason, an error message is send back over the socket. I modified the helper binary to first try to connect to that socket, and if that fails for whatever reason to just fall back to `am`. That should make it robust to unimplemented argument parsing, you just lose the extra speed. Because the system is just added to the rest of the plugin, no refactoring of existing features is necessary (was that the reason communication over sockets wasn't implemented yet?).  
  
I have the debug build of Termux installed on my S7 anyways, so I could test the performance increase.  
`termux-battery-info` now runs in 0.06s  
  
I don't know how fast it would be if you cut out the intent altogether and do everything over sockets, but an order of magnitude seems to be a pretty good improvement.  
  
Should I submit a PR or is there no chance for this to get merged?

**Comment by xalexalex** [comment]
IIRC some work was ongoing on a very similar thing. I can't find the PR but a few posts above there's an interesting link: https://github.com/Epictek/termux-api/commit/6a16ace08dec6922ce88806c54e52c6fea706155 . You might want to take a look and possibly join forces.

**Comment by Grimler91** [comment]
Yeah, the old [sockets branch](https://github.com/termux/termux-api/commits/sockets) changed to using sockets instead, giving a very big speed increase. 

I tried continue the work there but largely gave up due to java not being my strong side.. :) 

Maybe your implementation is better in any case @tareksander, feel free to open a PR and I am sure with can give this issue some attention again.
