### ISSUE TITLE
termux-api-media-scan

### ISSUE THREAD

**Issue by rgh36167** [termux/termux-api#70]
I have several scripts which manipulate picture galleries and need a way to initiate a media scan once the images are modified.

When using am to send ACTION_MEDIA_MOUNTED or ACTION_MEDIA_SCANNER_SCAN_FILE I get a permission problem:
`Broadcasting: Intent { act=android.intent.action.MEDIA_MOUNTED dat=file:///sdcard }
java.lang.SecurityException: Permission Denial: broadcast asks to run as user -2 but is calling from user 0; this
requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS`

Either this permission should be added or some dedicated primitive to termux-api, see also http://droidyue.com/blog/2014/01/19/scan-media-files-in-android/ for some info.

**Comment by fornwall** [comment]
Does it work if you specify `--user 0` when invoking `am`?

**Comment by rgh36167** [comment]
returns without error for ACTION_MEDIA_SCANNER_SCAN_FILE, doesn't work for MEDIA_MOUNTED.

Will test if the rescan actually works later.

**Comment by fornwall** [comment]
MEDIA_MOUNTED seems to be protected and not permitted to be broadcasted from apps (starting from Android 4.4 according to http://stackoverflow.com/questions/24072489/java-lang-securityexception-permission-denial-not-allowed-to-send-broadcast-an).

**Comment by rgh36167** [comment]
I have got ACTION_MEDIA_SCANNER_FILE working but it is not a good solution: I can add files and have them scanned but deleted or moved files are not processed this way and still appear in the Gallery etc.

To support file deletion/move either MEDIA_MOUNTED would be needed or the solution outlined in  http://droidyue.com/blog/2014/01/19/scan-media-files-in-android/ 

Don't see any way to do it with the available shell commands?

**Comment by rgh36167** [comment]
Found a hackish way to "inform" the media scanner about (re)moved files:
* (re)move the file
* create an empty file with the exact same name and ask media scanner to scan it
* remove the fake file (after some grace period)

Seems to work though not very happy with the solution.

**Comment by brunelli** [comment]
I've started implementing a MediaScannerAPI because I have a related issue: I want my youtube-dl downloads to be visible on the gallery app.

Currently I have a working prototype of this and I hope to open a PR soon.

I'm implementing the CLI as termux-media-scan . It scans any file/path you pass as argument, and it can also scan recursively with the -r switch.

To scan deleted/moved files you'll need to call it with /full/path/to/old/file . This is needed because BusyBox's realpath implementation doesn't return a full path for non-existent files, thus it will do nothing if you have a deleted file ~/file.jpg and, having your working directory in ~ , runs termux-media-scan file.jpg . I'm studying alternative ways to handle this use case.
