### ISSUE TITLE
termux-clipboard-set doesn't work

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#8]
Hi,
"termux-clipboard-set" doesn't exit on my device. It seems to be stuck in a loop. It used to work before. 
I've recorded it here: https://asciinema.org/a/esqy5c1yyxk6vv2nf7xl48ugk

**Comment by fornwall** [comment]
The `termux-clipboard-set` script currently does not use any arguments, it only accepts input on stdin. So for now either pipe something to it:

    myprogram | termux-clipboard-set

or write it manually, then end input with Ctrl+D (end of file):

    $ termux-clipboard-set
    Text to put in clipboard
    <Ctrl+D>

It'll probably be a good idea to change termux-clipboard-set to optionally accept input as arguments instead of reading stdin!

**Comment by Neo-Oli** [comment]
Interesting. Then I must be mistaken in my remembering that it used to work
like that before.

**Comment by fornwall** [comment]
The `termux-clipboard-set` script has been updated to:

1. If arguments are given, as in `termux-clipboard-set text-to-set`, then this is put into the clipboard.
2. If no arguments are given, as in `env | termux-clipboard-set`, then the text on stdin is put into the clipboard (as previously).

**Comment by brainstorm** [comment]
This doesn't seem to hold anymore, it hangs for me as well :/

**Comment by fosslinux** [comment]
@fornwall
